parameters:
    mattsches_version_eye.client.class: Mattsches\VersionEyeBundle\Client\VersionEyeClient
    mattsches_version_eye.mattsches_version_eye.composer_loader.class: Mattsches\VersionEyeBundle\Service\ComposerLoader
    mattsches_version_eye.data_collector.version_eye.class: Mattsches\VersionEyeBundle\DataCollector\VersionEyeDataCollector
    mattsches_version_eye.filesystem_cache.class: Doctrine\Common\Cache\FilesystemCache
    mattsches_version_eye.filesystem_cache.path: /tmp

services:
    mattsches_version_eye.client:
        class: %mattsches_version_eye.client.class%
        arguments: [ %mattsches_version_eye.base_url% ]

    mattsches_version_eye.composer_loader:
        class: %mattsches_version_eye.mattsches_version_eye.composer_loader.class%
        arguments: [ "%kernel.root_dir%/../composer.json" ]

    mattsches_version_eye.filesystem_cache:
        class: %mattsches_version_eye.filesystem_cache.class%
        arguments: [ %mattsches_version_eye.filesystem_cache.path% ]

    mattsches_version_eye.data_collector.version_eye:
        class: %mattsches_version_eye.data_collector.version_eye.class%
        arguments: [ @mattsches_version_eye.client, %mattsches_version_eye.api_key%, @mattsches_version_eye.composer_loader, @mattsches_version_eye.filesystem_cache ]
        tags:
            - { name: data_collector, template: 'MattschesVersionEyeBundle:Collector:versioneye', id: 'version_eye' }
